# Default Configuration

spring:
  profiles:
    active: dev

  main:
    banner-mode: "off"

  jersey:
    servlet:
      load-on-startup: 1

  flyway:
    locations: "classpath:db/migrations"

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: false
        format_sql: false
        jdbc:
          lob:
            non_contextual_creation: true
    open-in-view: false

  sleuth:
    sampler:
      probability: 1
  zipkin:
    sender:
      type: web

server:
  port: 8000
  error:
    include-stacktrace: never
    whitelabel:
      enabled: false
    include-exception: false
  servlet:
    context-path: /
  compression:
    enabled: true

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true

---
# Configuration for Development Environment

spring:
  profiles:
    - dev
    - development

  datasource:
    url: jdbc:postgresql://localhost:5432/coding-eval-platform__users-service
    username: coding-eval-platform__users-service
    password: coding-eval-platform__users-service

  jpa:
    properties:
      hibernate:
        format_sql: true
        show_sql: true

eureka:
  client:
    serviceUrl:
      defaultZone: "http://localhost:8761/eureka/"

users-service:
  first-user:
    username: administrator
    password: -_FirstUser1_-

---
# Configuration for Staging Environment

spring:
  profiles:
    - staging

---
# Configuration for Production Environment

spring:
  profiles:
    - prod
    - production
