# Default Configuration

spring:
    profiles:
        active: dev

    main:
        banner-mode: "off"


    jpa:
        hibernate:
            ddl-auto: none
        properties:
            hibernate:
                show_sql: false
                format_sql: false
                jdbc:
                    lob:
                        non_contextual_creation: true
        open-in-view: false

server:
    port: 8000
    error:
        include-stacktrace: never
        whitelabel:
            enabled: false
        include-exception: false
    servlet:
        context-path: /
    compression:
        enabled: true

---
# Configuration for Development Environment

spring:
    profiles:
        - dev
        - development

    datasource:
        url: jdbc:postgresql://localhost:5432/coding-eval-platform__users-service
        username: coding-eval-platform__users-service
        password: coding-eval-platform__users-service

    jpa:
        properties:
            hibernate:
                format_sql: true
                show_sql: true

    flyway:
        locations: "classpath:db/migrations"

---
# Configuration for Staging Environment

spring:
    profiles:
        - staging

---
# Configuration for Production Environment

spring:
    profiles:
        - prod
        - production
